
BIBER=biber
PDFLATEX=pdflatex -file-line-error -interaction=nonstopmode -output-directory . -jobname $(OUTPUT) $(PROJECT)
BIBTEX=bibtex
RM = rm -rf

REVISION = $(abspath ../build/revision.tex)
 
UNAME := $(shell uname)
 
# $(call convert_to_png, input.pdf, output,png)
define convert_to_png_lnx
	convert -density 150 $(1) -quality 90 $(2)
endef
define convert_to_png_mac
	sips -s format png --out $(2) $(1)
endef
 
all: $(OUTPUT).pdf
 
$(OUTPUT).pdf : *.tex $(REVISION)
	$(PDFLATEX)
	# $(BIBTEX) $(OUTPUT)
	# $(BIBER) $(OUTPUT).bcf
	$(PDFLATEX)
	$(PDFLATEX)

docker: *.tex
	docker run -v `pwd`:/source noah95/latex /usr/bin/make

$(REVISION):
	mkdir -p $(dir $(REVISION))
	echo "% Autogenerated, do not edit" > $(REVISION)
	echo "\\\newcommand{\\\revisiondate}{`git log -1 --format=\"%ad\" --date=iso`}" >> $(REVISION)
	echo "\\\newcommand{\\\revision}{`git log -1 --format=\"%h\"`}" >> $(REVISION)
	echo "\\\newcommand{\\\compiledate}{`date \"+%Y-%m-%d %H:%M:%S\"`}" >> $(REVISION)
	echo "\\\newcommand{\\\hostname}{`hostname`}" >> $(REVISION)

clean:
	$(RM) *.aux *.bbl *.blg *.log *.out *.pdf build
